solution_grid = [["", "", "", "", ""], ["", "", "", "", ""], ["", "", "", "", ""], ["", "", "", "", ""], ["", "", "", "", ""]]

[clues]
col_clues = [["", ""], ["", ""], ["", ""], ["", ""], ["", ""]]
row_clues = [["", ""], ["", ""], ["", ""], ["", ""], ["", ""]]
